### ISSUE TITLE
A bug in webapps-annex/app/js/annex.js line 335-340

### ISSUE THREAD

**Issue by GMBale** [01org/webapps-annex#8]
The below code from webapps-annex/app/js/annex.js seems to be a bug.
<pre><code>335            if (this.step >= 50)
336                this.level += 1;
337            else if (this.setp >= 53)
338                this.level += 1;
339            else if (this.step >= 55)
340                this.level += 2;</code></pre>
In line 337, "setp" seems to be a typo.
Moreover, the second and third branches are unreachable in line 337-340.

**Comment by davidmaxwaterman** [comment]
thanks!
